version: '3.8'

services:
  nextjs-frontend:
    build:
      context: .
      dockerfile: Dockerfile-front-admin
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    stdin_open: true
    tty: true
